-- Your SQL goes here
CREATE TABLE cv_entries (
  id SERIAL PRIMARY KEY,
  title TEXT DEFAULT NULL,
  content TEXT DEFAULT NULL,
  tags TEXT DEFAULT NULL,
  src TEXT DEFAULT NULL,
  start_date TEXT DEFAULT NULL,
  end_date TEXT DEFAULT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
